<template>
  <div class="about pa-6">
    <h1>About what?</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nisl tortor, pulvinar nec tincidunt non, pharetra ut eros. Nullam auctor, sem in varius molestie, felis eros varius eros, nec viverra augue erat posuere mauris. Morbi ornare turpis vel orci blandit, pretium gravida lectus viverra. Sed at est velit. Vivamus eget mollis nulla. Pellentesque a condimentum est, a mattis massa. Pellentesque dignissim nunc nec lacus feugiat, et maximus sem lobortis. Vestibulum euismod odio vitae quam euismod vulputate eget non erat. Mauris convallis dolor sem. Mauris dapibus neque tortor, eget semper elit mattis id. Duis rutrum venenatis ultricies. Donec ultricies condimentum ornare.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nisl tortor, pulvinar nec tincidunt non, pharetra ut eros. Nullam auctor, sem in varius molestie, felis eros varius eros, nec viverra augue erat posuere mauris. Morbi ornare turpis vel orci blandit, pretium gravida lectus viverra. Sed at est velit. Vivamus eget mollis nulla. Pellentesque a condimentum est, a mattis massa. Pellentesque dignissim nunc nec lacus feugiat, et maximus sem lobortis. Vestibulum euismod odio vitae quam euismod vulputate eget non erat. Mauris convallis dolor sem. Mauris dapibus neque tortor, eget semper elit mattis id. Duis rutrum venenatis ultricies. Donec ultricies condimentum ornare.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut nisl tortor, pulvinar nec tincidunt non, pharetra ut eros. Nullam auctor, sem in varius molestie, felis eros varius eros, nec viverra augue erat posuere mauris. Morbi ornare turpis vel orci blandit, pretium gravida lectus viverra. Sed at est velit. Vivamus eget mollis nulla. Pellentesque a condimentum est, a mattis massa. Pellentesque dignissim nunc nec lacus feugiat, et maximus sem lobortis. Vestibulum euismod odio vitae quam euismod vulputate eget non erat. Mauris convallis dolor sem. Mauris dapibus neque tortor, eget semper elit mattis id. Duis rutrum venenatis ultricies. Donec ultricies condimentum ornare.</p>

  </div>
</template>
